-- Seed CMS Data from static files

INSERT INTO leaders (name, role, designation, bio, image_url, phone, display_order) VALUES
('Ashwani Mishra', 'Rashtriya Adhyaksh — HinduVahini', 'President', 'Shri Ashwani Mishra ji leads HinduVahini''s national mission with unwavering dedication to Hindu cultural values.', '/uploads/leaders_img/ashwani_mishra.jpg', '+91 99355 68569', 0),
('Anand Tiwari', 'Goraksha Pramukh — HinduVahini', 'Leader', 'Shri Anand Tiwari ji heads all campaigns related to cow protection and welfare.', '/uploads/leaders_img/anand_tiwari.jpeg', '+91 90444 87748', 1),
('Vimal Mishra', 'Rashtriya Mahasachiv — HinduVahini', 'Leader', 'Shri Vimal Mishra ji guides the strategic initiatives and organizational expansion.', '/uploads/leaders_img/vimal_mishra.jpeg', '+91 9415643345', 2),
('Ruchin Sharma', 'Pradesh Rajneetik Salahkar — HinduVahini', 'Leader', 'Shri Ruchin Sharma ji provides crucial political and sociological advisory.', '/uploads/leaders_img/ruchin_sharma.jpeg', '+91 84291 00010', 3),
('Surender Kumar', 'Rashtriya upadhyaksh — HinduVahini', 'Leader', 'Shri Surender Kumar ji coordinates security and discipline across statewide events.', '/uploads/leaders_img/surendra_kumar.jpeg', '+91 9812113501', 4),
('Akshay Sharma', 'Pardesh Adhyaksh, Haryana — HinduVahini', 'Leader', 'Shri Akshay Sharma ji is dedicated to the organizational mission and cultural outreach.', '/uploads/leaders_img/akshay_sharma.jpeg', '+91 9050096403', 5),
('Akhilesh Dwivedi', 'Pradesh Adhyaksh Uttar Pradesh', 'Leader', 'Shri Akhilesh Dwivedi ji represents core organizational viewpoints in significant assemblies.', '/uploads/leaders_img/akhilesh_dviwedi.jpeg', '+91 9451010762', 6),
('Dayanand', 'Pardesh Mahamantgri Harayana — HinduVahini', 'Leader', 'Dedicated to the organizational mission and cultural outreach.', '/uploads/leaders_img/dayanand.jpeg', '+91 9992768186', 7),
('Karan Singh', 'Pardesh Mahasachiv Haryana — HinduVahini', 'Leader', 'Dedicated to the organizational mission and cultural outreach.', '/uploads/leaders_img/karan_singh.jpeg', '+91 8053906786', 8),
('Vijay Nandan', 'Pardesh Adhyaksh Bihar — HinduVahini', 'Leader', 'Dedicated to the organizational mission and cultural outreach.', '/uploads/leaders_img/vijay_nandan.jpeg', '+91 8002104335', 9);

INSERT INTO gallery_images (image_url, span_classes, display_order) VALUES
('/uploads/gallery_img/g1.jpeg', 'row-span-2 col-span-2', 0),
('/uploads/gallery_img/g2.jpeg', 'row-span-1 col-span-1', 1),
('/uploads/gallery_img/g3.jpeg', 'row-span-1 col-span-1', 2),
('/uploads/gallery_img/g4.jpeg', 'row-span-1 col-span-2 md:col-span-1', 3),
('/uploads/gallery_img/g11.jpeg', 'row-span-2 col-span-1', 4),
('/uploads/gallery_img/g6.jpeg', 'row-span-1 col-span-1', 5),
('/uploads/gallery_img/g7.jpeg', 'row-span-1 col-span-1', 6),
('/uploads/gallery_img/g8.jpeg', 'row-span-1 col-span-1', 7),
('/uploads/gallery_img/g9.jpeg', 'row-span-2 col-span-2', 8),
('/uploads/gallery_img/g10.jpeg', 'row-span-1 col-span-1', 9),
('/uploads/gallery_img/g7 (2).jpeg', 'row-span-1 col-span-1', 10),
('/uploads/gallery_img/g12.jpeg', 'row-span-1 col-span-2 md:col-span-1', 11),
('/uploads/gallery_img/g13.jpeg', 'row-span-2 col-span-1', 12),
('/uploads/gallery_img/g14.jpeg', 'row-span-1 col-span-1', 13),
('/uploads/gallery_img/g15.jpeg', 'row-span-1 col-span-1', 14),
('/uploads/gallery_img/g16.jpeg', 'row-span-2 col-span-1', 15),
('/uploads/gallery_img/g17.jpeg', 'row-span-1 col-span-1', 16),
('/uploads/gallery_img/g18.jpeg', 'row-span-1 col-span-1', 17),
('/uploads/gallery_img/g19.jpeg', 'row-span-1 col-span-2 md:col-span-1', 18),
('/uploads/gallery_img/g20.jpeg', 'row-span-1 col-span-1', 19),
('/uploads/gallery_img/g5.jpeg', 'row-span-1 col-span-1', 20),
('/uploads/gallery_img/g21.jpeg', 'row-span-1 col-span-1', 21),
('/uploads/gallery_img/g22.jpeg', 'row-span-1 col-span-1', 22),
('/uploads/gallery_img/g23.jpeg', 'row-span-2 col-span-2', 23),
('/uploads/gallery_img/g24.jpeg', 'row-span-1 col-span-1', 24),
('/uploads/gallery_img/g25.jpeg', 'row-span-1 col-span-1', 25),
('/uploads/gallery_img/g26.jpeg', 'row-span-2 col-span-1', 26),
('/uploads/gallery_img/g27.jpeg', 'row-span-1 col-span-1', 27),
('/uploads/gallery_img/g28.jpeg', 'row-span-1 col-span-1', 28),
('/uploads/gallery_img/g29.jpeg', 'row-span-1 col-span-2 md:col-span-1', 29),
('/uploads/gallery_img/g30.jpeg', 'row-span-1 col-span-1', 30),
('/uploads/gallery_img/g31.jpeg', 'row-span-1 col-span-1', 31),
('/uploads/gallery_img/g32.jpeg', 'row-span-2 col-span-2', 32),
('/uploads/gallery_img/g33.jpeg', 'row-span-1 col-span-1', 33),
('/uploads/gallery_img/g34.jpeg', 'row-span-1 col-span-1', 34),
('/uploads/gallery_img/g35.jpeg', 'row-span-2 col-span-1', 35),
('/uploads/gallery_img/g36.jpeg', 'row-span-1 col-span-1', 36),
('/uploads/gallery_img/g37.jpeg', 'row-span-1 col-span-1', 37),
('/uploads/gallery_img/g38.jpeg', 'row-span-1 col-span-2 md:col-span-1', 38),
('/uploads/gallery_img/g39.jpeg', 'row-span-1 col-span-1', 39),
('/uploads/gallery_img/g40.jpeg', 'row-span-1 col-span-1', 40),
('/uploads/gallery_img/g41.jpeg', 'row-span-2 col-span-2', 41),
('/uploads/gallery_img/g42.jpeg', 'row-span-1 col-span-1', 42),
('/uploads/gallery_img/g43.jpeg', 'row-span-1 col-span-1', 43),
('/uploads/gallery_img/g44.jpeg', 'row-span-2 col-span-1', 44);
